# General behavior
variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .cache/pip
    - .venv

stages:
  - lint
  - test
  - docs

# Templates
.on_merge_tag_or_manual: &on_merge_tag_or_manual
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success
    - if: $CI_COMMIT_TAG
      when: on_success
    - when: manual

.install-deps: &install-deps
  before_script:
    - pip install --upgrade pip
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry install  # Ensure dependencies are installed
    - poetry run make setup

.test-template: &test
  <<: *on_merge_tag_or_manual
  <<: *install-deps
  stage: test
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  script: poetry run make test

# Lint
lint:
  <<: *on_merge_tag_or_manual
  <<: *install-deps
  stage: lint
  script:
    - |
      changed_files=$(git diff --name-only $CI_MERGE_REQUEST_TARGET_BRANCH_SHA $CI_MERGE_REQUEST_SOURCE_BRANCH_SHA | grep '\.py$')
      if [ -n "$changed_files" ]; then
        poetry run flake8 $changed_files
      else
        echo "No Python files changed."
      fi
  image: python:3.10

# Tests
python3.10:
  <<: *test
  image: python:3.10

python3.11:
  <<: *test
  image: python:3.11

python3.11.9:
  <<: *test
  image: python:3.11.9

# Docs
pages:
  <<: *install-deps
  image: python:3.10
  stage: docs
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success
  script:
    - poetry run make docs
    - mv docs/build/html public/
  artifacts:
    paths:
      - public
