# General behavior
variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .cache/pip
    - .venv

stages:
  - lint
  - test
  - docs

# Templates
.on_merge_tag_or_manual: &on_merge_tag_or_manual
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success
    - if: $CI_COMMIT_TAG
      when: on_success
    - when: manual

.install-deps: &install-deps
  before_script:
    - pip install poetry==1.0.10
    - poetry config virtualenvs.in-project true
    - make setup

.test-template: &test
  <<: *on_merge_tag_or_manual
  <<: *install-deps
  stage: test
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  script: make test

# Lint
lint:
  <<: *on_merge_tag_or_manual
  <<: *install-deps
  stage: lint
  script: make lint
  image: python:3.8

# Tests
python3.6:
  <<: *test
  image: python:3.6

python3.7:
  <<: *test
  image: python:3.7

python3.8:
  <<: *test
  image: python:3.8

python3.9:
  <<: *test
  image: python:3.9

# Docs
pages:
  <<: *install-deps
  image: python:3.8
  stage: docs
  when: manual
  # rules:
  #   - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  #       when: on_success
  script: 
    - make docs
    - mv docs/build/html public/
  artifacts:
    paths:
    - public
