# General behavior
variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .cache/pip
    - .venv

stages:
  - lint
  - test
  - docs

# Templates
.on_merge_tag_or_manual: &on_merge_tag_or_manual
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success
    - if: $CI_COMMIT_TAG
      when: on_success
    - when: manual

.install-deps: &install-deps
  before_script:
    - pip install --upgrade pip
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry install  # Ensure dependencies are installed
    - poetry run make setup

.test-template: &test
  <<: *on_merge_tag_or_manual
  <<: *install-deps
  stage: test
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  script: poetry run make test

# # Lint
# lint:
#   <<: *on_merge_tag_or_manual
#   <<: *install-deps
#   stage: lint
#   script:
#     - time poetry run flake8
#   image: python:3.10
#   cache:
#     paths:
#       - .venv

# Tests
python3.10:
  <<: *test
  image: python:3.10

python3.11:
  <<: *test
  image: python:3.11
  
python3.12:
  <<: *test
  image: python:3.12

# Docs
pages:
  <<: *install-deps
  image: python:3.10
  stage: docs
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success
  script:
    - poetry run make docs
    - mv docs/build/html public/
  artifacts:
    paths:
      - public
