# General behavior
variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .cache/pip
    - .venv

stages:
  - lint
  - test

# Templates
.on_merge_tag_or_manual: &on_merge_tag_or_manual
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always
    - if: $CI_COMMIT_TAG
      when: always
    - when: manual

.install-deps: &install-deps
  before_script:
    - pip install poetry
    - poetry --version
    - poetry config virtualenvs.in-project true
    - poetry install -vv

.test-template: &test
  <<: *on_merge_tag_or_manual
  <<: *install-deps
  stage: test
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  script: make test

# Lint
lint:
  <<: *on_merge_tag_or_manual
  <<: *install-deps
  stage: lint
  script: make lint
  image: python:3.8

# Tests
python3.7:
  <<: *test
  image: python:3.7

python3.8:
  <<: *test
  image: python:3.8
